// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASi9B5H8Q6VdzK46rb2IO8N-1bGFhKNIo',
    appId: '1:914736784954:web:9fb57c802a50591591b703',
    messagingSenderId: '914736784954',
    projectId: 'zoomclone-bc04b',
    authDomain: 'zoomclone-bc04b.firebaseapp.com',
    storageBucket: 'zoomclone-bc04b.appspot.com',
    measurementId: 'G-W0SH8SBWT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24lnHhlNpZsnnJYGjLePS7Kq8KKDLPCg',
    appId: '1:914736784954:android:c3f4325372cce58491b703',
    messagingSenderId: '914736784954',
    projectId: 'zoomclone-bc04b',
    storageBucket: 'zoomclone-bc04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_nWXUuGDqrNr0NgQy5XkFdNsBaGv1lg',
    appId: '1:914736784954:ios:2781b96e238b3de091b703',
    messagingSenderId: '914736784954',
    projectId: 'zoomclone-bc04b',
    storageBucket: 'zoomclone-bc04b.appspot.com',
    iosBundleId: 'com.example.zoomclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_nWXUuGDqrNr0NgQy5XkFdNsBaGv1lg',
    appId: '1:914736784954:ios:edb8b52c7a4ca8d491b703',
    messagingSenderId: '914736784954',
    projectId: 'zoomclone-bc04b',
    storageBucket: 'zoomclone-bc04b.appspot.com',
    iosBundleId: 'com.example.zoomclone.RunnerTests',
  );
}
